name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  buildFrontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build frontend
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"
          cache-dependency-path: client/package-lock.json
      - run: |
          cd client/
          npm ci
      - run: |
          cd client/
          npm run build --if-present
